version: "3.2"
# Need .env with DB_PASSWORD, DB_NAME

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./:/usr/src/app
    depends_on:
      - postgres
    networks:
      - app-network
    environment:
      SECRET: some-secret
      DB_USERNAME: postgres
      DB_DIALECT: postgres
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      NODE_ENV: ${NODE_ENV:-development}
      DB_HOST: postgres
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - app-network
    volumes:
      - db:/var/lib/postgresql/data
  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - app-network

volumes:
  db:
networks:
  app-network:
    driver: bridge 
